[tool.poetry]
name = "cookie_python"
version = "0.0.1"
description = ""
authors = ["Stephen Kent <smkent@smkent.net>"]

[tool.poetry.dependencies]
python = "^3.8"
setuptools_scm = "*"

[tool.poetry.dev-dependencies]
build = "*"
black = "*"
flake8 = "*"
isort = "*"
mypy = "*"
pipenv-setup = "*"
pytest = "*"
pytest-cookies = "*"
pytest-cov = "*"
pytest-sugar = "*"
pyyaml = "*"
tox = "*"
tox-pipenv = "*"
types-PyYAML = "*"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"

[tool.isort]
atomic = true
profile = "black"
line_length = 79

[tool.mypy]
files = ["tests"]
disallow_untyped_defs = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
show_error_codes = true
warn_unused_ignores = true

# vim: ft=cfg
