[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "cookie_python"
version = "0.0.1"
description = ""
authors = ["Stephen Kent <smkent@smkent.net>"]

[tool.poetry.dependencies]
python = "^3.8"
poetry-dynamic-versioning = "^0.13.1"

[tool.poetry.dev-dependencies]
build = "*"
black = "*"
flake8 = "*"
isort = "*"
mypy = "*"
pytest = "*"
pytest-cookies = "*"
pytest-cov = "*"
pytest-sugar = "*"
pyyaml = "*"
tox = "*"
types-PyYAML = "*"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"

[tool.isort]
atomic = true
profile = "black"
line_length = 79

[tool.mypy]
files = ["tests"]
disallow_untyped_defs = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
show_error_codes = true
warn_unused_ignores = true

[tool.pytest.ini_options]

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py38
isolated_build = True

[testenv]
deps =
    black
    flake8
    isort
    mypy
    pytest
    pytest-cov
    pytest-sugar
commands =
    flake8 -- .
    isort --quiet --check-only -- tests/ hooks/
    black -l 79 -q --check --diff --color -- tests/ hooks/
    mypy
    pytest
allowlist_externals = python

[gh-actions]
python =
    3.8: py38
"""

# vim: ft=cfg
