---
name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-test-publish:
    name: "Python ${{ "{{" }} matrix.python-version }}"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - "3.10"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "${{ "{{" }} matrix.python-version }}"

      - name: 🐍 Install dependencies
        run: python -m pip install --upgrade pip pipenv

      - name: 🛠 Build
        run: make

      - name: 🔥 Test
        run: make test

      - name: 📊 Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true

      - name: 📦 Build package
        run: make dist

      # - name: 🔼 Upload to Test PyPI
      #   uses: pypa/gh-action-pypi-publish@master
      #   with:
      #     password: ${{ "{{" }} secrets.TEST_PYPI_API_TOKEN }}
      #     repository_url: https://test.pypi.org/legacy/
      #     skip_existing: true

      # - name: ☢ Upload to PyPI
      #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      #   uses: pypa/gh-action-pypi-publish@master
      #   with:
      #     password: ${{ "{{" }} secrets.PYPI_API_TOKEN }}

concurrency:
  group: ci-tests-${{ "{{" }} github.ref }}-1
  cancel-in-progress: true
